import random

dictionary = {
    "cat": "mushuk",
    "dog": "it",
    "bird": "qush",
    "Freezing": "sovuq",
    "Frustrate": "Ko'nglini qoldirmoq",
    "frivolous": "engiltak",
    "fetch": "Olib kelmoq",
    "gate": "darvoza",
    "gain": "yig`moq",
    "glad": "xursand",
    "Grape": "uzum",
    "Grocery store": "supermarket",
    "guide": "yo`l ko'rsatmoq",
    "get out": "bu yerdan ket",
    "gender": "jins",
    "gambling": "qimor",
    "hit": "urmoq",
    "heat": "isitmoq",
    "heavy": "og`ir",
    "hurt": "jarohatlamoq",
    "hope": "umid qilmoq",
    "honest": "rostgo`y",
    "helicopter": "vertalyot",
    "honor": "sharaf",
    "head=go": "bormoq",
    "horrific": "qo`rqinchli",
    "indentification": "pasport",
    "immediately": "tezda",
    "improve": "yaxshilamoq",
    "intermediate": "o`rta daraja",
    "include=involve": "o`z ichiga olmoq",
    "insect": "hashorat",
    "face": "duch kelmoq",
    "fail": "muvofiyatsizlikka uchramoq",
    "fair": "adolat",
    "fall": "yiqilmoq",
    "fill": "to`ldirmoq",
    "find out": "bilib olmoq",
    "fit": "mos tushmoq",
    "fog": "tuman",
    "foggy": "tumanli",
    "follow": "ergashmoq",
    "foreign": "chet ellik",
    "in front of": "oldida",
    "join": "qo`shilmoq",
    "journey": "sayohat",
    "juvenile": "voyaga yetmagan",
    "jargon": "Texnik til",
    "jeopardiza=risk": "tavakkal qilmoq",
    "kick": "tepmoq",
    "kit": "maxsus kiyim",
    "knowledgeable": "aqilli",
    "keep doing": "qishloqda davom etmoq",
    "laptop": "kompyuter",
    "large=huge": "katta",
    "late": "kech",
    "at least": "kamida",
    "leather": "teri",
    "leave": "tark etmoq",
    "left-handed": "chapaqay",
    "eviol":"iblis",
    "cram":"tushunmasdan yodlash",
    "cross":"kesib o`tmoq",
    "crowd":"olamon",
    "cycle":"velosiped haydamoq",
    "customer":"xaridor",
    "circumstance":"holat",
    "creativ":"ijodkor",
    "commute (to)":"ga bormoq qatnamoq",
    "conscience":"vijdon, g`urur",
    "consider":"deb hisoblamoq",
    "dangerous":"xavfli",
    "delay":"kechiktrmoq, ortga surmoq",
    "dentist":"tish shifokor",
    "desert":"sahro",
    "dessert":"shirinlik",
    "dairy products":"sut maxsulotlari",
    "differ":"farq qilmoq",
    "differentiate":"ajratmoq",
    "describe":"tasvirlamoq",
    "dirty":"kir",
    "discount":"chegirma",
    "discuss":"muhokama qilmoq",
    "dish":"ovqat, taom",
    "download":"yuklamoq",
    "draw":"durrang",
    "defeat":"mag`lubiyat",
    "dream about":"tush ko'rmoq",
    "dream of":"orzu qilmoq",
    "driving lincence":"haydovchilik guvohnomasi",
    "dive(into)":"sho`ng`imoq",
    "electricity":"elektr toki",
    "else":"yana",
    "erase":"o'chirmoq",
    "exciting":"qiziqarli",
    "excuse=pretext":"baxona",
    "extra":"qo'shimcha",
    "evoke":"uyg'otmoq",
    "endeavor":"urinib ko'rmoq",
    "extinet":"qirilib ketgan",
    "to be eager to":"qilishni hohlamoq",
    "entail":"sabab bo'lmoq",
    "e-book":"elektron kitob",
    "establish":"o'rnatmoq, asos solmoq",
    "evolve":"rivojlanmoq",
    "earthquake":"zilzila",
    "road":"yo'l",
    "roast":"qovurmoq",
    "rock":"qoya",
    "roof":"tom",
    "round":"dumaloq",
    "roundabout":"aylana yo'l",
    "rubber":"o'chirg'ich",
    "roll":"o'ramoq",
    "requer":"talab qilmoq",
    "release":"ozod qilmoq",
    "reinforce":"kuchaytirmoq",
    "roller coaster":"attraksion",
    "riddle":"topishmoq",
    "rib":"qovirg'a",
    "resume":"qayta boshlamoq",
    "rumor":"mish mish",
    "save":"saqlamoq",
    "searf":"sharf",
    "science":"ilm fan",
    "scissors":"qayta",
    "screen":"ekran",
    "sea":"dengiz",
    "seat":"o'rindiq",
    "sell":"sotmoq",
    "send":"yubormoq",
    "sentence":"gap",
    "serve":"xizmat ko'rsatmoq",
    "set (a goal)":"qo'ymoq (maqsad)",
    "several":"bir necha",
    "surmount":"yengmoq",
    "swallow":"yutmoq",
    "slightly":"oz-moz",
    "sequence":"ketma-ketlik",
    "put":"qo'ymoq",
    "put on":"kiymoq",
    "penalize":"jazolamoq",
    "prevail=exist":"mavjud bo'lmoq",
    "pure":"shaffof",
    "predetermine":"oldindan belgilamoq",
    "plausible":"haqiqatga yaqin",
    "pompous":"dabdabali",
    "pervert":"hayoli buziq",
    "preach":"diniy maruza o'qimoq",
    "quarter":"chorak",
    "question":"shubhaga solmoq",
    "quick":"tezkor",
    "quiet":"tinch",
    "quite":"ancha",
    "quiz":"bosh qotirma",
    "queue":"navbat",
    "race":"poyga",
    "Railway":"temir yo'l",
    "raincoat":"plash",
    "rap":"sal turtmoq",
    "reason":"sabab",
    "receipt":"chek",
    "receive":"qabul qilmoq",
    "refrigerator":"muzlatkich",
    "rent":"ijara olmoq",
    "repair":"tuzatmoq",
    "repeat":"qaytarmoq",
    "rehearse":"ripititsiya qilmoq",
    "rest":"dam olish",
    "return":"qaytmoq",
    "ride":"haydamoq (ot,velosiped)",
    "river":"daryo",
    "rhyme":"qofiya",
    "revise":"takrorlamoq",
    "register":"ro'yhatdan o'tmoq",
    "Rare":"kamyob",
    "rhino":"korkidon",
    "reverse":"to'ntarmoq",
    "rural":"qishloqqa oid",
    "rejuvenate":"qayta kuchga kirmoq",
    "retreat":"qaytarib olmoq",
    "regular":"doimiy",
    "sad":"qayg'uli",
    "sail":"suzmoq",
    "sale":"savdo",
    "salt":"tuz",
    "same":"bir xil",
    "sauce":"sous",
    "sausage":"sosiska",
    "i don't mind":"qarshi emasman",
    "never mind":"hechqisi yoq",
    "mirror":"ko'zgu",
    "modern=contemperary":"zamonaviy",
    "mountain":"tog'",
    "mug":"krujka",
    "mushroom":"qo'ziqorin",
    "moron":"ahmoq",
    "messy":"iflos",
    "mention":"eslatmoq",
    "the majorty of...":"ning ko'pchiligi",
    "mostly=most of all":"ko'p xollarda",
    "multiply(by)":"ko'paytirmoq",
    "museum":"muzey",
    "marvel":"mo'jiza",
    "lend":"qarz bermoq",
    "let sb do sth":"ruxsat bermoq biron narsa qilishni",
    "lie":"aldamoq",
    "lift":"ko'tarmoq",
    "lay":"to'shamoq",
    "look after":"g'amxo'rlik qilmoq",
    "look for":"qidirmoq",
    "look at":"ga qaramoq",
    "look out":"ehtiyot bo'l!",
    "loose":"katta va qulay (kiyimga nisbatan)",
    "loud":"yuqori ovozda",
    "lovely":"yoqimli",
    "low":"past",
    "lounge":"dam olish xonasi",
    "lean on":"suyanmoq",
    "mumble":"shivirlamoq",
    "near":"yaqinida",
    "nearly":"deyarli",
    "neck":"bo'yin",
    "necklace":"marjon",
    "neighbor":"qo'shni",
    "nationality":"millat",
    "net":"tarmoq",
    "noise/noisy":"shovqin/ shovqinli",
    "naive":"sodda",
    "nose":"burun",
    "natice":"payqamoq",
    "nurse":"hamshira",
    "narrow":"tor",
    "natural":"tabiiy",
    "nimble=foxy":"ayyor",
    "nod":"bosh irg'imoq",
    "narrov-minded":"tot fikirlovchi",
    "instead":"o'rniga",
    "invite":"taklif qilmoq",
    "idol":"qahramon",
    "idle away time":"behuda vaqt sarflamoq",
    "immitate":"taqlid qilmoq",
    "irreplaceable":"o'rnini bosib bo'lmaydigan",
    "inner":"ichki",
    "innate":"tug'ma",
    "intrusive":"shilqim",
    "immortal":"o'lmas",
    "impair":"yomonlashmoq",
    "infamous=notoriouse":"mashhur (yomon tomonlama)",
    "imply (at)":"nazarda tutmoq",
    "jewelry":"taqinchoq",
    "seldom":"kamdan-kam",
    "settle (a problem)":"yechmoq",
    "severe":"qattiq",
    "slow":"sekin",
    "scarce":"oz",
    "soul":"ko'ngil",
    "superior":"yaxshiroq",
    "sand":"qum",
    "sluggish":"erinchoq",
    "struggle":"kurashmoq",
    "swear":"qasam ichmoq",
    "stride":"katta qadam qoymoq",
    "square":"kvadrat",
    "surrender=give up":"taslim bo'lmoq",
    "shame":"sharmanda",
    "shampoo":"shampun",
    "sheep":"qo'y",
    "arrive":"yetib kelmoq",
    "art":"sanat",
    "attractive":"o'ziga tortuvchi",
    "available":"bor,mavjud",
    "awful":"daxshat",
    "back":"bel",
    "backpack":"ryugzak",
    "behind":"orqada",
    "belong (to)":"tegishli bo'lmoq",
    "beside":"yonida",
    "besides that=moreover":"bundan tawqari",
    "blanket":"ko'rpa",
    "board game":"stol o'yini",
    "borrow":"qarz olib turmoq",
    "both":"ikkalasi",
    "brave":"qo'rqmas",
    "sheet":"varoq",
    "shelf":"javon",
    "ship":"kema",
    "shirt":"ko'ylak",
    "shoe":"poyabzal",
    "snack":"yengil ovqat",
    "slowly":"sekin",
    "snowboard":"chang'i",
    "soap":"sovun",
    "sock":"paypoq",
    "soft":"yumshoq",
    "software":"taminlovchi dastur",
    "sound":"tovush",
    "soup":"shorva",
    "space":"fazo",
    "spare":"bo'sh",
    "spell":"harflab aytmoq",
    "spoon":"qoshiq",
    "spend (on)":"o'tkazmoq",
    "staff":"hodimlar",
    "temperature":"harorat",
    "tent":"chodir",
    "term":"atama",
    "terrible":"daxshat",
    "textbook":"darslik",
    "than":"ga qaraganda",
    "then":"keyin/ o'shanda",
    "theater":"teatr",
    "thin":"oriq",
    "thirtsy":"chanqagan",
    "through":"orqali",
    "throw":"otmoq",
    "thounderstorm":"momaqaldiroq",
    "ticket":"bilet",
    "tidy":"toza",
    "tie":"kalustiq",
    "tight":"tor",
    "sneeze":"aksirmoq",
    "shallow":"sayoz",
    "shrink":"yelka qismoq",
    "sneaker":"krasofka",
    "shrug":"ko'tarmoq (yelkalarni)",
    "soothe":"tinchlantirmoq",
    "swell":"shishmoq",
    "slight":"anchagina",
    "stink":"sasimoq",
    "take on":"kiymoq",
    "take off":"yechmoq",
    "tall":"uzun",
    "teach":"o'qitmoq",
    "team":"jamoa",
    "tell":"aytmoq",
    "till":"gacha",
    "timetable":"jadval",
    "tired":"charchagan",
    "toast":"tostar",
    "toe":"oyoq barmoqlari",
    "together":"birgalikda",
    "too":"juda",
    "toothbrush":"tish cho'tka",
    "top":"yuqori",
    "tour":"sayohat",
    "total":"jami",
    "towel":"sochiq",
    "toy":"o'yinchoq",
    "traffic":"harakat",
    "traffic light":"svetafor",
    "trainer":"keta",
    "tram":"tramvay",
    "trouble":"muammo",
    "trousers":"shim",
    "shout":"qichqirmoq",
    "shower":"dush",
    "shut":"yopmoq",
    "sick":"kasal",
    "side":"tomom",
    "sightseeing":"diqqatga sazavor joy",
    "sign":"imzo chekmoq",
    "silver":"kumush",
    "sing":"kuylamoq",
    "singer":"qo'shiqchi",
    "sink":"rakvina",
    "site":"o'rin",
    "size":"o'lcham",
    "skiing":"chang'ida uchmoq",
    "skirt":"yubka",
    "sleepy":"uyquchi",
    "slice":"bo'lak",
    "slim":"nozik",
    "stage":"sahna",
    "stairs":"zina",
    "stamp":"muhr",
    "stay":"qolmoq",
    "steak":"go'sht",
    "steal":"o'g'irlamoq",
    "still":"hali ham",
    "stomach":"qorin",
    "stomach ache":"qorin og'rig'i",
    "store":"saqlamoq",
    "strom":"bo'ron",
    "story":"ertak",
    "straight":"to'g'ri",
    "strange":"g'alati",
    "study":"o'qimoq",
    "subject":"fan",
    "suddenly":"to'satdan",
    "van":"vagon",
    "vase":"vaza",
    "vote":'ovoz bermoq',
    "vacuum eleaner":"changyutkich",
    "vet":"veterinar",
    "velocity":"tezlik",
    "vary":"farq",
    "vanquish":"yutmoq",
    "vigorous":"tetik",
    "waiter":"afitsiyant",
    "wake up":"uyg'onmoq",
    "walk=stroll":"sayr qilmoq",
    "wall":"devor",
    "wallet":"hamyon",
    "washing machine":"kiryuvish mashinasi",
    "way":"yo'l",
    "true":"to'g'ri",
    "to be able to":"ga qodir bolmoq",
    "agree":"rozi bolmoq",
    "accident":"baxtsiz xodisa",
    "actually":"aslida",
    "advertisement":"reklama",
    "adult":"vayaga yetgan inson",
    "adventure":"sarguzasht",
    "advice":"maslahat",
    "almost":"deyarli",
    "alone":"yolg'iz",
    "amezing=excellent":"ajoyib",
    "among":"orasida (3 dan kop)",
    "appartment nulding":"kop qavatli turar joy",
    "apologize":"kechirim so'rash",
    "unacceptable":"nomaqbul",
    "unavoidable=inevitable":"muqarrar",
    "uncertain":"ishonchsiz",
    "underestimate":"yetarli baho bermaslik",
    "uncomfortable":"noquulay",
    "Unconditional=unlimited":"cheklanmagan",
    "unconscious":"hushsiz",
    "undeniable":"shubhasiz",
    "underdog":"yutishga imkoniyati kam bo'lgan",
    "undegraduate":"bitiruvchi",
    "unite":"birlashmoq",
    "unversal":"Jahon halqaro",
    "unless":"qilma guncha",
    "unleash":"bo'shatish",
    "up-to-date = latest":"dolzarb",
    "urban":"shaharga oid",
    "urgent":"shoshilinch",
    "useful":"foydali",
    "unsuitable":"to'g'ri kelmasydigan",
    "undertake":"kirishmoq",
    "undermine":"ishonchga putur",
    "upstairs":"yuqori qavat",
    "versus":"qarshi",
    "varienty":"xilma-xillik",
    "various":"har xil",
    "view":"ko'rinish",
    "village":"qishloq",



}


print("BAZADA HOZIRCHA 450 SO'Z BOR")


print("Savollar sonini kiriting:")
a=int(input())

def generate_question():
    question = random.choice(list(dictionary.keys()))
    correct_answer = dictionary[question]

    other_options = random.sample(list(dictionary.values()), k=3)
    options = [correct_answer] + other_options
    random.shuffle(options)

    return question, options, correct_answer


def run_test():
    score = 0

    for _ in range(a):  # 5 ta savol uchun test o'tkazamiz, siz o'zgartirishingiz mumkin
        question, options, correct_answer = generate_question()

        print(f"{_+1}) Inglizcha so'z:👉🏻 {question} 👈🏻 🤔?")

        for i, option in enumerate(options):
            print(f"{chr(65 + i)}) {option}")

        choice = input("Javobingizni tanlang ⏳: ")
        choice_index = ord(choice.upper()) - 65

        if choice_index >= 0 and choice_index < len(options):
            chosen_option = options[choice_index]
            if chosen_option == correct_answer:
                print("To'g'ri!☺️👍🏻✅")
                score += 1
            else:
                print(f"Noto'g'ri!👎🏻❌ To'g'ri javob: ➡️{correct_answer}⬅️ 🤦🏻‍♂️")
        else:
            print("Noto'g'ri tanlov!")

        print()

    print(f"Test natijasi🥳 : {score} / {a}")   #  n ta savol uchun test natijasini chiqaramiz


# Testni boshlash
run_test()

